version: '3.9'
services:

  postgres:
    container_name: sipacks-postgres-dev
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sipacks-backend-dev
    image: sipacks-backend
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
      HTTP_DEBUG: 'true'

    ports:
      - 8080:8080
    depends_on:
      - postgres

  frontend:
    container_name: sipacks-frontend-dev
    image: sipacks-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  pg-data:

