version: '3.9'
services:

  postgres:
    container_name: sipacks-postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  app:
    build: .
    container_name: sipacks-backend
    image: sipacks-backend
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - tmp:/tmp

volumes:
  pg-data:
  tmp: