ALTER TABLE "pack" DROP CONSTRAINT IF EXISTS "pack_fk0";

ALTER TABLE "pack_tag" DROP CONSTRAINT IF EXISTS "pack_tag_fk0";

ALTER TABLE "pack_tag" DROP CONSTRAINT IF EXISTS "pack_tag_fk1";

DROP TABLE IF EXISTS "pack_tag";
DROP TABLE IF EXISTS "pack";
DROP TABLE IF EXISTS "tag";
DROP TABLE IF EXISTS "author";
